CREATE TABLE IF NOT EXISTS "LiteLLM_MCPServerTable" (
    server_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    server_name TEXT,
    alias TEXT,
    description TEXT,
    instructions TEXT,
    url TEXT,
    spec_path TEXT,
    transport TEXT NOT NULL DEFAULT 'sse',
    auth_type TEXT,
    credentials JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    mcp_info JSONB NOT NULL DEFAULT '{}',
    mcp_access_groups JSONB NOT NULL DEFAULT '[]',
    allowed_tools JSONB NOT NULL DEFAULT '[]',
    tool_name_to_display_name JSONB NOT NULL DEFAULT '{}',
    tool_name_to_description JSONB NOT NULL DEFAULT '{}',
    extra_headers JSONB NOT NULL DEFAULT '[]',
    static_headers JSONB NOT NULL DEFAULT '{}',
    env_vars JSONB NOT NULL DEFAULT '[]',
    status TEXT DEFAULT 'unknown',
    last_health_check TIMESTAMP(3),
    health_check_error TEXT,
    command TEXT,
    args JSONB NOT NULL DEFAULT '[]',
    env JSONB NOT NULL DEFAULT '{}',
    authorization_url TEXT,
    token_url TEXT,
    registration_url TEXT,
    oauth2_flow TEXT,
    allow_all_keys BOOLEAN NOT NULL DEFAULT FALSE,
    available_on_public_internet BOOLEAN NOT NULL DEFAULT TRUE,
    delegate_auth_to_upstream BOOLEAN NOT NULL DEFAULT FALSE,
    oauth_passthrough BOOLEAN NOT NULL DEFAULT FALSE,
    is_byok BOOLEAN NOT NULL DEFAULT FALSE,
    byok_description JSONB NOT NULL DEFAULT '[]',
    byok_api_key_help_url TEXT,
    source_url TEXT,
    timeout DOUBLE PRECISION,
    approval_status TEXT DEFAULT 'active',
    submitted_by TEXT,
    submitted_at TIMESTAMP(3),
    reviewed_at TIMESTAMP(3),
    review_notes TEXT
);

CREATE INDEX IF NOT EXISTS mcp_server_approval_status_idx ON "LiteLLM_MCPServerTable" (approval_status);
CREATE INDEX IF NOT EXISTS mcp_server_alias_idx ON "LiteLLM_MCPServerTable" (alias);
