pub mod repository;
pub mod schema;
pub(crate) mod write;

pub(crate) const SELECT_COLS: &str = r#"
    server_id,
    server_name,
    alias,
    description,
    instructions,
    url,
    spec_path,
    transport,
    auth_type,
    credentials,
    CAST(EXTRACT(EPOCH FROM created_at) * 1000 AS BIGINT) AS created_at,
    created_by,
    CAST(EXTRACT(EPOCH FROM updated_at) * 1000 AS BIGINT) AS updated_at,
    updated_by,
    mcp_info,
    mcp_access_groups,
    allowed_tools,
    tool_name_to_display_name,
    tool_name_to_description,
    extra_headers,
    static_headers,
    env_vars,
    status,
    CAST(EXTRACT(EPOCH FROM last_health_check) * 1000 AS BIGINT) AS last_health_check,
    health_check_error,
    command,
    args,
    env,
    authorization_url,
    token_url,
    registration_url,
    oauth2_flow,
    allow_all_keys,
    available_on_public_internet,
    delegate_auth_to_upstream,
    oauth_passthrough,
    is_byok,
    byok_description,
    byok_api_key_help_url,
    source_url,
    timeout,
    approval_status,
    submitted_by,
    CAST(EXTRACT(EPOCH FROM submitted_at) * 1000 AS BIGINT) AS submitted_at,
    CAST(EXTRACT(EPOCH FROM reviewed_at) * 1000 AS BIGINT) AS reviewed_at,
    review_notes
"#;
