use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::FromRow;

#[derive(Debug, Clone, FromRow, Serialize)]
pub struct McpServerRow {
    pub server_id: String,
    pub server_name: Option<String>,
    pub alias: Option<String>,
    pub description: Option<String>,
    pub instructions: Option<String>,
    pub url: Option<String>,
    pub spec_path: Option<String>,
    pub transport: String,
    pub auth_type: Option<String>,
    pub credentials: Value,
    pub created_at: i64,
    pub created_by: Option<String>,
    pub updated_at: i64,
    pub updated_by: Option<String>,
    pub mcp_info: Value,
    pub mcp_access_groups: Value,
    pub allowed_tools: Value,
    pub tool_name_to_display_name: Value,
    pub tool_name_to_description: Value,
    pub extra_headers: Value,
    pub static_headers: Value,
    pub env_vars: Value,
    pub status: Option<String>,
    pub last_health_check: Option<i64>,
    pub health_check_error: Option<String>,
    pub command: Option<String>,
    pub args: Value,
    pub env: Value,
    pub authorization_url: Option<String>,
    pub token_url: Option<String>,
    pub registration_url: Option<String>,
    pub oauth2_flow: Option<String>,
    pub allow_all_keys: bool,
    pub available_on_public_internet: bool,
    pub delegate_auth_to_upstream: bool,
    pub oauth_passthrough: bool,
    pub is_byok: bool,
    pub byok_description: Value,
    pub byok_api_key_help_url: Option<String>,
    pub source_url: Option<String>,
    pub timeout: Option<f64>,
    pub approval_status: Option<String>,
    pub submitted_by: Option<String>,
    pub submitted_at: Option<i64>,
    pub reviewed_at: Option<i64>,
    pub review_notes: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct CreateMcpServer {
    pub server_name: Option<String>,
    pub alias: Option<String>,
    pub description: Option<String>,
    pub instructions: Option<String>,
    pub url: Option<String>,
    pub spec_path: Option<String>,
    pub transport: Option<String>,
    pub auth_type: Option<String>,
    pub credentials: Option<Value>,
    pub mcp_info: Option<Value>,
    pub mcp_access_groups: Option<Value>,
    pub allowed_tools: Option<Value>,
    pub tool_name_to_display_name: Option<Value>,
    pub tool_name_to_description: Option<Value>,
    pub extra_headers: Option<Value>,
    pub static_headers: Option<Value>,
    pub env_vars: Option<Value>,
    pub status: Option<String>,
    pub command: Option<String>,
    pub args: Option<Value>,
    pub env: Option<Value>,
    pub authorization_url: Option<String>,
    pub token_url: Option<String>,
    pub registration_url: Option<String>,
    pub oauth2_flow: Option<String>,
    pub allow_all_keys: Option<bool>,
    pub available_on_public_internet: Option<bool>,
    pub delegate_auth_to_upstream: Option<bool>,
    pub oauth_passthrough: Option<bool>,
    pub is_byok: Option<bool>,
    pub byok_description: Option<Value>,
    pub byok_api_key_help_url: Option<String>,
    pub source_url: Option<String>,
    pub timeout: Option<f64>,
    pub approval_status: Option<String>,
    pub submitted_by: Option<String>,
    pub review_notes: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct UpdateMcpServer {
    pub server_name: Option<String>,
    pub alias: Option<String>,
    pub description: Option<String>,
    pub instructions: Option<String>,
    pub url: Option<String>,
    pub spec_path: Option<String>,
    pub transport: Option<String>,
    pub auth_type: Option<String>,
    pub credentials: Option<Value>,
    pub mcp_info: Option<Value>,
    pub mcp_access_groups: Option<Value>,
    pub allowed_tools: Option<Value>,
    pub tool_name_to_display_name: Option<Value>,
    pub tool_name_to_description: Option<Value>,
    pub extra_headers: Option<Value>,
    pub static_headers: Option<Value>,
    pub env_vars: Option<Value>,
    pub status: Option<String>,
    pub command: Option<String>,
    pub args: Option<Value>,
    pub env: Option<Value>,
    pub authorization_url: Option<String>,
    pub token_url: Option<String>,
    pub registration_url: Option<String>,
    pub oauth2_flow: Option<String>,
    pub allow_all_keys: Option<bool>,
    pub available_on_public_internet: Option<bool>,
    pub delegate_auth_to_upstream: Option<bool>,
    pub oauth_passthrough: Option<bool>,
    pub is_byok: Option<bool>,
    pub byok_description: Option<Value>,
    pub byok_api_key_help_url: Option<String>,
    pub source_url: Option<String>,
    pub timeout: Option<f64>,
    pub approval_status: Option<String>,
    pub submitted_by: Option<String>,
    pub submitted_at: Option<i64>,
    pub reviewed_at: Option<i64>,
    pub review_notes: Option<String>,
}
